In [1]:
import numpy as np 

In [2]:
r = np.array([[0, 1], [2, 3]])
g = np.array([[4, 5], [6, 8]])
b = np.array([[9, 1], [1, 1]])

In [3]:
np.stack([r, g, b], axis=0)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 8]],

       [[9, 1],
        [1, 1]]])

In [4]:
np.vstack((r, g, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 8],
       [9, 1],
       [1, 1]])

In [5]:
np.hstack((r, g, b))

array([[0, 1, 4, 5, 9, 1],
       [2, 3, 6, 8, 1, 1]])

In [6]:
np.stack((r, g, b), axis=-1)

array([[[0, 4, 9],
        [1, 5, 1]],

       [[2, 6, 1],
        [3, 8, 1]]])